import {EnglishTikTokConfig} from './EnglishTikTokShort';

export const agentMemoryEnglishConfig: EnglishTikTokConfig = {
  episode: 'MEMORY · EN',
  accent: '#FFD154',
  hook: ['CHAT HISTORY', 'IS NOT MEMORY'],
  verdict: 'More context is not a memory system.',
  failureTitle: 'A longer prompt still forgets',
  failurePath: ['Replay chat', 'Context trimmed', 'Preference lost'],
  exampleTitle: 'One durable developer preference',
  before: ['127 messages', 'Replay noise, cost and irrelevant history'],
  after: ['1 record', 'user.pref.language = TypeScript'],
  fixTitle: 'Retrieve only what matters',
  fixPath: ['Write', 'Retrieve', 'Inject'],
  close: ['History is raw material.', 'Memory is the system.'],
  footer: 'WRITE · RETRIEVE · UPDATE · DELETE',
  narrationPath: 'audio/narration-elevenlabs-en.wav',
  bgmPath: 'audio/music-ai-news-49.mp3',
  actorLabel: 'TS PREF',
  journeyNodes: ['CHAT', 'CONTEXT', 'TASK', 'SHORT', 'LONG', 'RETRIEVE'],
  mechanismStates: [
    {from: 0, to: 205, node: 0, label: 'Replayed chat ≠ memory', tone: 'failure'},
    {from: 205, to: 327, node: 1, label: 'Trim context → lose detail', tone: 'failure'},
    {from: 327, to: 553, node: 2, label: 'Separate three memory layers', tone: 'neutral'},
    {from: 553, to: 814, node: 1, label: '127 messages bury one preference', tone: 'failure'},
    {from: 814, to: 922, node: 4, label: 'Store one structured record', tone: 'success'},
    {from: 922, to: 1098, node: 5, label: 'Retrieve only when relevant', tone: 'success'},
    {from: 1098, to: 1365, node: 5, label: 'Write · Retrieve · Update · Delete', tone: 'success'},
  ],
  captions: [
    {from: 9, to: 200, lines: ['Does replaying every chat give an AI agent memory?', 'No. It only gives the model more current context.']},
    {from: 205, to: 322, lines: ['Switch threads or trim the context window,', 'and those details disappear.']},
    {from: 327, to: 548, lines: ['Production memory needs three layers:', 'task state, short-term and long-term memory.']},
    {from: 553, to: 809, lines: ['“All my projects use TypeScript.”', 'Replaying 127 messages buries that preference.']},
    {from: 814, to: 917, lines: ['Store one structured record instead,', 'keyed to the user.']},
    {from: 922, to: 1092, lines: ['Retrieve it only when relevant,', 'then inject it into context.']},
    {from: 1098, to: 1328, lines: ['Chat history is raw material.', 'Agent memory manages write, retrieve, update and delete.']},
  ],
};
