import React from 'react';
import {AbsoluteFill, Img, interpolate, Easing, staticFile, useCurrentFrame} from 'remotion';
const lime='#D8F590',paper='#F8F7EF',dark='#17211F';
const ease=Easing.bezier(.16,1,.3,1);
const tween=(f:number,a:number,b:number,x:number,y:number)=>interpolate(f,[a,b],[x,y],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:ease});
const Panel:React.FC<{title:string;x:number;y:number;w:number;h:number;f:number;delay?:number;tilt?:number;children:React.ReactNode}>=({title,x,y,w,h,f,delay=0,tilt=0,children})=><div style={{position:'absolute',left:x,top:y,width:w,height:h,background:paper,color:dark,border:`3px solid ${dark}`,outline:`3px solid ${paper}`,borderRadius:23,boxShadow:'12px 15px 0 #0008',overflow:'hidden',transform:`translateY(${tween(f,delay,delay+12,80,0)}px) rotate(${tilt}deg) scale(${tween(f,delay,delay+12,.91,1)})`,opacity:tween(f,delay,delay+7,0,1)}}><div style={{height:55,borderBottom:`2px solid ${dark}`,display:'flex',alignItems:'center',gap:20,padding:'0 23px',background:'#E9ECDD',fontFamily:'monospace',fontSize:22,fontWeight:700}}><span style={{letterSpacing:6}}>●○○</span>{title}</div><div style={{padding:30}}>{children}</div></div>;
const Tag:React.FC<{children:React.ReactNode}>=({children})=><span style={{display:'inline-block',padding:'12px 22px',border:`2px solid ${dark}`,borderRadius:12,background:lime,fontSize:29,fontWeight:650}}>{children}</span>;
const Big:React.FC<{children:React.ReactNode}>=({children})=><div style={{fontSize:58,fontWeight:800,lineHeight:1.2,marginBottom:22}}>{children}</div>;
const Block:React.FC<{children:React.ReactNode;active?:boolean}>=({children,active=false})=><div style={{padding:'19px 25px',border:`2px solid ${dark}`,borderRadius:13,background:active?lime:'#fff',fontSize:30,fontWeight:650,textAlign:'center'}}>{children}</div>;
const Head:React.FC<{n:string;title:string;sub:string}>=({n,title,sub})=><div style={{position:'absolute',left:105,top:144}}><div style={{color:lime,fontSize:25,letterSpacing:3,marginBottom:15}}>{n} / 带你一步步，把项目做出来</div><div style={{fontSize:76,fontWeight:800,letterSpacing:-2}}>{title}</div><div style={{fontSize:29,color:'#C1CEC4',marginTop:14}}>{sub}</div></div>;
export const Outro:React.FC=()=>{
 const f=useCurrentFrame();const stage=f<38?0:f<76?1:f<116?2:f<158?3:4;const s=f-[0,38,76,116,158][stage];
 return <AbsoluteFill style={{background:'radial-gradient(ellipse at 50% 65%,#34473E,#101715 75%)',fontFamily:'"PingFang SC",sans-serif',color:paper,overflow:'hidden'}}>
 <div style={{position:'absolute',left:100,top:45,display:'flex',alignItems:'center',gap:25}}><Img src={staticFile('logo.png')} style={{width:205,height:58,objectFit:'contain'}}/><span style={{fontSize:24,letterSpacing:2}}>AI ENGINEER · 第七期</span></div>
 <div style={{position:'absolute',right:100,top:59,color:lime,fontSize:25}}>每周理论 + 实践 · 13 周项目实践</div>
 {stage===0&&<><Head n="01" title="AI Coding → 可运行 MVP" sub="从需求、界面到业务流程，把项目真正跑起来。"/>
 <Panel title="01 / TASK BRIEF" x={118} y={411} w={505} h={449} f={s} tilt={-5}><Big>先定义<br/>要做什么。</Big><Block>需求 → 验收标准</Block><div style={{fontSize:28,marginTop:28}}>AI Rules · ADLC</div></Panel>
 <Panel title="02 / AI CODING" x={663} y={389} w={520} h={480} f={s} delay={3}><Big>用 AI<br/>把产品做出来。</Big><div style={{background:dark,color:lime,padding:23,borderRadius:12,fontSize:28,fontFamily:'monospace',lineHeight:1.7}}>CareKind.project<br/>› UI + API + Database<br/>› Review + Test</div></Panel>
 <Panel title="03 / BUSINESS MVP" x={1229} y={411} w={545} h={449} f={s} delay={6} tilt={5}><Big>跑通<br/>完整业务流程。</Big><Block active>任务 → 记录 → 确认</Block><div style={{fontSize:28,marginTop:28}}>同一个 CareKind 项目持续升级</div></Panel></>}
 {stage===1&&<><Head n="02" title="把 AI 能力，接进你的项目。" sub="Voice AI · RAG · MCP Tools"/>
 {['VOICE AI','POLICY RAG','MCP TOOLS'].map((t,i)=><Panel key={t} title={t} x={116+i*570} y={410+(i===1?-20:0)} w={540} h={465} f={s} delay={i*3} tilt={[-4,0,4][i]}><Big>{['语音变成\n可确认的记录','让回答\n有据可查','让 AI\n调用真实工具'][i].split('\n').map((x,n)=><React.Fragment key={x}>{n>0&&<br/>}{x}</React.Fragment>)}</Big><Block active>{['语音 → 转写 → 人工确认','检索 → 引用 → 验证','工具发现 → 权限 → 调用'][i]}</Block><div style={{fontSize:28,marginTop:28}}>{['STT · Editable Transcript','先建立评测，再验证 RAG','Typed Contracts · Tool Calling'][i]}</div></Panel>)}</>}
 {stage===2&&<><Head n="03" title="Multi-Agent：学会让 AI 协作。" sub="架构 + Lab · 任务分工、独立上下文、结果汇总"/>
 <Panel title="MULTI-AGENT / ORCHESTRATION" x={130} y={389} w={1050} h={500} f={s} tilt={-2}><div style={{width:460,margin:'0 auto'}}><Block active>Coordinator · 协调任务</Block></div><div style={{textAlign:'center',fontSize:44,lineHeight:1.3,color:'#718044'}}>↙　　　　　　　　　↘</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:35}}><Block>Specialist A · 执行</Block><Block>Specialist B · 检查</Block></div><div style={{textAlign:'center',fontSize:40,lineHeight:1.2,color:'#718044'}}>↘　　　　　　　　　↙</div><Block active>验证结果 · 汇总交付</Block></Panel>
 <Panel title="LEARN + BUILD" x={1250} y={410} w={530} h={500} f={s} delay={4} tilt={4}><Big>不只会调用。<br/>还要会编排。</Big><div style={{display:'flex',gap:14,flexWrap:'wrap'}}><Tag>Handoff</Tag><Tag>Context</Tag><Tag>Memory</Tag></div><div style={{fontSize:27,marginTop:25}}>比较质量、延迟与协作成本</div></Panel></>}
 {stage===3&&<><Head n="04" title="Harness + LLM Routing" sub="把 Agent 做成受控、可恢复、可评测的生产系统。"/>
 <Panel title="PRODUCTION HARNESS" x={120} y={400} w={785} h={483} f={s} tilt={-3}><Big>让 Agent<br/>稳定运行。</Big><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:15}}>{['Hooks · 权限','Budget · 预算','Checkpoint · 恢复','Trace · 追踪'].map((x,i)=><Block key={x} active={i===Math.floor(s/8)%4}>{x}</Block>)}</div></Panel>
 <Panel title="LLM / MODEL ROUTING" x={985} y={400} w={805} h={510} f={s} delay={3} tilt={3}><Big>让任务<br/>找到合适的模型。</Big><div style={{display:'flex',alignItems:'center',gap:15}}><Tag>Task</Tag><span style={{fontSize:34}}>→</span><Tag>Policy Router</Tag></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14,marginTop:22}}><Block active>Model A</Block><Block>Model B</Block></div><div style={{fontSize:26,marginTop:19}}>质量 · 成本 · 延迟 · 隐私 · Fallback</div></Panel></>}
 {stage===4&&<><div style={{position:'absolute',top:157,left:105,fontSize:83,fontWeight:800}}>带你一步步，<span style={{color:lime}}>把项目做出来。</span></div>
 <div style={{position:'absolute',left:130,right:130,top:335,display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:22}}>{['AI Coding','Voice AI','RAG','MCP Tools','Multi-Agent','Memory','Harness','LLM Routing'].map((x,i)=><div key={x} style={{background:paper,color:dark,borderRadius:15,padding:'25px 10px',textAlign:'center',fontSize:35,fontWeight:750,border:'3px solid #B9CD94',transform:`translateY(${tween(s,i%4*2,12+i%4*2,40,0)}px) rotate(${i%2===0?-2:2}deg)`,opacity:tween(s,i%4*2,8+i%4*2,0,1)}}>{x}</div>)}</div>
 <div style={{position:'absolute',top:639,left:130,fontSize:31,color:'#C1CEC4'}}>Evals · Governance · 安全与故障演练 · Demo Day</div>
 <div style={{position:'absolute',left:126,top:737,fontSize:77,fontWeight:800,color:lime}}>AI Engineer 第七期 <span style={{fontSize:45}}>↗</span></div><div style={{position:'absolute',left:132,top:858,fontSize:30}}>三年打磨 · 循序渐进 · 系统学习</div></>}
 <div style={{position:'absolute',bottom:41,left:105,right:105,display:'flex',gap:10}}>{[0,1,2,3,4].map(i=><div key={i} style={{height:5,flex:1,background:i<=stage?lime:'#405046'}}/>)}</div>
 </AbsoluteFill>;
};
